### ISSUE TITLE
Bug报告：网速过慢时传输文件会不完整

### ISSUE THREAD

**Issue by hoixding** [Ikaros-521/Implementation-of-TCP-File-Transfer-in-C-under-Linux#1]
server.c在实现tcp传输时没有实际校验文件块的传输效果，而是使用写死延迟的方法保证文件传输完毕，这种方法限制了文件传输的速度，同时也导致文件传输在低网速是的不稳定性，试了几次，可以确定的是大文件几乎不能成功...

**Comment by Ikaros-521** [comment]
确实有这个问题 可以做成传输一段后 确认传输是否完成，这样还可以加上本次传输的数据长度、md5校验值等，增加传输的可靠性。简单封装个协议，不过确实这个程序过于简陋了，问题还是比较多的，哪天有空我优化优化

**Comment by hoixding** [comment]
sorry，我用github还不是很熟练。
这些协议可以参考bt和ftp做成haeder，在发送前就为文件分好bitch，每个bitch做计数之类的。希望能帮到你

**Comment by Ikaros-521** [comment]
是的 再往下做就直接做成ftp了 23333
这个小程序当初只是做为小作业的形式完成的，后面稍微把大文件的问题处理了一下，再往下做下去就会复杂很多
其实也算是闲置了0.0 不过有空可能会继续往下推进
